#!/usr/bin/env python

"""Poteau Web

Usage:
    poteau-web

"""

from pyelasticsearch import ElasticSearch

from poteau import Kibana
from poteau.apache import combined, documents_from_combined


if __name__ == "__main__":
    import sys

    # Instantiate it with an url
    es = ElasticSearch(sys.argv[1])
    # Kibana need this kind of name
    k = Kibana(es)
    logs = combined(sys.stdin)
    for day, size in k.index_documents('combined',
                                       documents_from_combined(logs)):
        print("[%s] #%i" % (day, size))
